
compiler:
    - gcc
    - clang

language: objective-c

before_install:
 - brew update && brew outdated gcc-arm-none-eabi || brew upgrade gcc-arm-none-eabi && brew outdated cmake || brew upgrade cmake

script:
 - export REV=dirty-$(git describe --always)
 - mkdir dist
 - mkdir -p tools/buildxcode
 - cd  $TOP/tools/buildxcode 
 - cmake -G "Xcode" .. -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_BUILD_TYPE=Release 
 - ls -l
 - xcodebuild -list
 - xcodebuild -target psp2-fixup -configuration Release
 - xcodebuild -target install -configuration Release
 - cd $PREFIX
 - ls -l
 - ls -l bin
 - brew info gcc-arm-none-eabi

env:
 global:
  - TOP=$PWD
  - PREFIX=$TOP/dist 




