
compiler:
    - gcc
    - clang

language: objective-c

before_install:
 - brew update && brew outdated gcc-arm-none-eabi || brew upgrade gcc-arm-none-eabi && brew outdated cmake || brew upgrade cmake

script:
 - export REV=dirty-$(git describe --always)
 - mkdir out
 - mkdir -p tool/buildxcode
 - push tools/buildxcode 
 - cmake -G "Xcode" .. -DCMAKE_INSTALL_PREFIX=$(PATH_INSTALL) -DCMAKE_BUILD_TYPE=Release 
 - xcodebuild -target psp2-fixup -configuration Release -scheme install
 - cd ../../out
 - ls -l

env:
 global:
  - PATH_INSTALL="$PWD/out"




